### ISSUE TITLE
Extend with Aspects generator

### ISSUE THREAD

**Issue by patroza** [tim-smart/tsplus-json#2]
Based on (vscode snippet)
```json
"/**",
" * @tsplus type $1/$2.Aspects",
" */",
"export interface $2Aspects {}",
"",
"/**",
" * @tsplus static $1/$2.Ops $",
" */",
"export const $2: $2Aspects = {}"
```

and make them available in `/Aspects` of each tsplus package

**Comment by tim-smart** [comment]
Feel free to PR some more Aspects. Example: https://github.com/tim-smart/tsplus-json/blob/main/config/effect__io/src/Aspects.d.ts
